global:
  marketplace-ami: false
  owner: yuval@spotinst.com
  qsname: quickstart-spotinst-ecs
  regions:
    - us-east-1
    - us-west-2
  reporting: true
tests:
  quickstart-spotinst-ecs-vpc:
    parameter_input: sample-cloudformation-input-withvpc.json
    template_file: Elastigroup-ECS-Master.template
